apiVersion: apps/v1
kind: Deployment
metadata:
  name: dil-connector-gui
  namespace: dil-connector-gui
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: dil-connector-gui
  template:
    metadata:
      labels:
        app: dil-connector-gui
    spec:
      serviceAccountName: dil-connector-gui
      containers:
        - name: dil-connector-gui
          image: ghcr.io/data-space-lab/dil-connector-gui:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: dil-connector-gui-config
            - secretRef:
                name: dil-connector-gui-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
              ephemeral-storage: 1Gi
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
