apiVersion: v1
kind: Service
metadata:
  name: dil-connector-gui
  namespace: dil-connector-gui
spec:
  selector:
    app: dil-connector-gui
  ports:
    - name: http
      port: 8000
      targetPort: http
